schema_version: 1

project:
  name: fixture.git-project

profiles:
  - type: example
    config: project.example.yml

dependencies:
  - name: tool.java-project
    role: tooling
    type: git-submodule
    url: https://github.com/brainboxemb/tool.java-project.git
    path: tools/tool.java-project
    ref: dc94cf120ea4a196c9fc3daff4d22984ea4481c1
